Feature/1 add import functionality
mig-frankfurt/dataelementhub.dal pull request #4
Opened 2022-01-04 08:51 UTC by Ammarbr

**What's in the PR**
* ...

**How to test manually**
* ...

2022-01-14 14:49 UTC, michael-82 requested changes
Commit 7b858fe9125650911e2780af7b249616cce54221 deleted all jooq generated files. That does not seem correct.

2022-01-18 10:24 UTC, michael-82 requested changes

2022-01-18 12:37 UTC, Ammarbr commented on src/main/resources/de/dataelementhub/db/migration/V1_8__Update_import_tables.sql
> +    'INTERRUPTED',
changed to ABORTED

2022-01-18 12:39 UTC, Ammarbr commented on src/main/resources/de/dataelementhub/db/migration/V1_8__Update_import_tables.sql
> +ALTER TABLE staging ADD COLUMN staged_element_id text;
The standard for stagedElementId is the old urn (if we are importing an auto generated export file from dehub)

2022-01-26 15:05 UTC, michael-82 approved these changes

2022-01-26 15:05 UTC, merged